# Generated by Django 5.2.4 on 2025-07-27 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_cart_cartitem_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
